name: Deploy Equidistant

on:
  workflow_run:
    workflows: [Node.js CI]
    types:
      - completed
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'frontend/my-app'

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm run build --if-present    
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build